# Generated by Django 4.0 on 2021-12-09 02:59

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCharge',
            fields=[
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('debtor_name', models.CharField(max_length=255, verbose_name='nome do devedor')),
                ('loan_date', models.DateTimeField(verbose_name='data do empréstimo')),
                ('date_to_receive', models.DateTimeField(verbose_name='data à receber')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='valor')),
                ('debtor_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone do devedor')),
                ('details', models.TextField(blank=True, verbose_name='detalhes')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('debtor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user', verbose_name='devedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.user', verbose_name='dono')),
            ],
            options={
                'verbose_name': 'historical cobrança',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('debtor_name', models.CharField(max_length=255, verbose_name='nome do devedor')),
                ('loan_date', models.DateTimeField(verbose_name='data do empréstimo')),
                ('date_to_receive', models.DateTimeField(verbose_name='data à receber')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='valor')),
                ('debtor_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone do devedor')),
                ('details', models.TextField(blank=True, verbose_name='detalhes')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='users.user', verbose_name='devedor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='users.user', verbose_name='dono')),
            ],
            options={
                'verbose_name': 'cobrança',
                'verbose_name_plural': 'cobranças',
                'ordering': ('-created',),
            },
        ),
    ]
